export const EXPORT_JOB_STATUSES = ['SCHEDULED', 'IN_PROGRESS', 'SUCCESSFUL', 'FAILED'];

export const EXPORT_JOB_TYPES = [
  'BURSAR_FEES_FINES',
  'CIRCULATION_LOG',
  'E_HOLDINGS',
  'BULK_EDIT',
  'AUTH_HEADINGS_UPDATES',
];

export const EXPORT_JOB_TYPES_REQUEST_MAP = {
  'BURSAR_FEES_FINES': ['BURSAR_FEES_FINES'],
  'CIRCULATION_LOG': ['CIRCULATION_LOG'],
  'E_HOLDINGS': ['E_HOLDINGS'],
  'AUTH_HEADINGS_UPDATES': ['AUTH_HEADINGS_UPDATES', 'FAILED_LINKED_BIB_UPDATES'],
};
